### ISSUE TITLE
Struttura dello Statuto

### ISSUE THREAD

**Issue by erolm-a** [GLUGSicilia/Statuto#1]
Lo statuto sarà scritto in Markdown, e poi riconvertito in HTML e vari altri formati facilmente esportabili.

Da specificare gli elementi dello statuto.

Riassunto della chat di Telegram:

Lo Statuto si basa molto su quello di InformaticaLibera ([ovvero questo](informaticalibera.info/Statuto) ).

## Principi fondamentali:
Libertà del socio. Rispetto di tutti gli organi, dai soci fino al Preside, della Netiquette e della Legge Italiana oltre che dello Statuto. Presenza di norme antifasciste e antiautocratiche.
Diritto al giusto processo in caso di controversie.

## Organi:

Colleggio dei Probiviri, con il potere di risolvere le controversie
Consiglio Direttivo, con poteri amministrativi e organizzativi.
**TODO: discutere sulle modalità di votazione e di riunione in assemblea**

## Disposizioni transitorie e finali
Da decidersi i giorni in cui votare per il primo Consiglio Direttivo, per il Colleggio dei Probiviri per il primo Presidente.

**Comment by mastrobirraio** [comment]
fare un atto pubblico da far firmare ad un notaio
fare un nostro atto costitutivo e un contratto associativo

**Comment by jstrong76** [comment]
non serve il notaio, si fa solo la registrazione dell'atto costitutivo alla camera di commercio, servono almeno 3 soci fondatori

**Comment by erolm-a** [comment]
@jstrong76 Nice. Comunque, è ora di decidere 3 cose:
1. chi è socio fondatore
2. quando iniziare a votare consiglio, collegio e robe varie e quindi mettere i loro nomi nell'atto costitutivo (credo)
3. quale sede
