### ISSUE TITLE
Sistema di voto

### ISSUE THREAD

**Issue by erolm-a** [GLUGSicilia/Statuto#5]
Metto qui la chat Telegram di cui si è discusso della cosa.

> ErolM^A, [12.11.16 01:44]
> Supponiamo che oggi creiamo l'applicazione.
> 
> Tutti i soci (cioè quelli che sono iscritti ufficialmente) avranno consegnati una chiave gpg privata. Quando ci sarà un'elezione essi useranno gpg per cifrare una stringa con la loro chiave privata (ovviamente cercando di evitare attacchi MITM). Il sistema di voto riceve il messaggio, crittografato e firmato dal socio, e lo decrittografa e verifica con la chiave pubblica. Ovviamente ci vuole un keyserver
> 
> ErolM^A, [12.11.16 01:45]
> Se qualcuno ha una chiave gpg tipo @PalinuroSec  o @EliAran non c'è bisogno di averne un'altra
> 
> Castix, [12.11.16 01:45]
> Mi sembra ottimo
> 
> Fabio, [12.11.16 01:46]
> uhm
> 
> ErolM^A, [12.11.16 01:46]
> Ora, l'idea sarebbe fare una webapp, perché non credo che tutti potranno votare davanti a un terminale, spesso infatti c'è solo il cell
> 
> Castix, [12.11.16 01:46]
> In questo caso il codice sorgente testimonia l'anonimato
> 
> ErolM^A, [12.11.16 01:47]
> [Risponde a Fabio]
> dicci
> 
> ErolM^A, [12.11.16 01:49]
> Allora, ci sono 2 casi. Caso 1: generiamo noi stessi la chiave, e sarebbe la cosa migliore. Caso 2: la genera la webapp per noi (ovviamente molto prima di un eventuale voto). Lo scambio dovrebbe avvenire in modo sicuro, per esempio diffie-hellman (non sono un esperto di security, correggetemi subito)
> 
> ErolM^A, [12.11.16 01:50]
> La chiave deve sempre e comunque avere una passphrase e tante altre cose varie
> 
> Fabio, [12.11.16 01:51]
> solo una cosa a cui tengo particolarmente: che intendi per webapp?
> 
> ErolM^A, [12.11.16 01:52]
> ottima domanda
> 
> Fabio, [12.11.16 01:52]
> IMHO la cosa migliore sarebbe un servizio REST
> 
> Fabio, [12.11.16 01:52]
> così poi ognuno può usare il frontend che preferisce
> 
> ErolM^A, [12.11.16 01:52]
> Volevo proporlo pure io
> 
> Fabio, [12.11.16 01:53]
> comunque una cosa del genere secondo me potrebbe funzionare
> 
> ErolM^A, [12.11.16 01:53]
> La cosa migliore sarebbe distribuire uno script in python che gestisce tutto, si fa in poche righe (requests etc.) e con una ragionevole sicurezza
> 
> ErolM^A, [12.11.16 01:53]
> Per i telefoni si dovrebe ricorrere obbligatoriamente ad app
> 
> Fabio, [12.11.16 01:54]
> magari c'è solo qualche dettaglio da rivedere a mente serena, ma il meccanismo di base ci sta
> 
> Fabio, [12.11.16 01:54]
> [Risponde a ErolM^A]
> con una webapp SPA è la stessa cosa di usare un'app nativa o uno script
> 
> Fabio, [12.11.16 01:54]
> solo che invece di girare nel proprio processo gira nel browser, e invece di usare java/objc/c#/c++ usa javascript
> 
> ErolM^A, [12.11.16 01:56]
> D'accordo
> 
> Fabio, [12.11.16 01:56]
> comunque non è importante, pubblicando l'API ognuno poi può farsi il client che preferisce

Il giorno dopo kypters ha scritto:
> Ci sono 4 cose importanti da tenere in considerazione in un sistema del genere, io sono partito da quello
> 
> 1. Il voto dev'essere verificabile (dev'essere provabile che sono stato io a emettere il voto)
> 2. Il voto dev'essere anonimo (non si deve sapere COSA ho votato)
> 3. Bisogna evitare che si voti più di una volta
> 4. Non ci dev'essere un'unica entità in grado di sapere tutto (ovvero, nessuno deve avere la chiave privata del server)
> 
> 
> Tenete presente che non sono un esperto di crittografia, quindi probabilmente ci sono un sacco di cose che si possono migliorare o che si devono sistemare
> 
> 
> La fase di enroll devo ancora definirla bene, comunque l'obiettivo è fare in modo che il server conosca una (o più) chiavi pubbliche per ogni utente abilitato al voto
> 
> 
> Per ogni votazione, l'utente invierebbe un blob contenente il proprio voto + un po' di roba per aumentare l'entropia (salt e timestamp?) criptati con la chiave pubblica del server + l'hash del tutto firmato con la propria chiave privata
> 
> 
> fin qui abbiamo la possibilità di sapere che un voto è autentico (voti firmati) e si evita che si voti più di una volta
> 
> 
> mancano solo il 2 e il 4, che vengono fregati dal fatto che qualcuno possiede la chiave privata del server, e ho pensato che il modo migliore è fare in modo che nessuno abbia la chiave privata del server, nemmeno il server stesso :D
> 
> fondamentalmente questa chiave serve soltanto al momento dello spoglio
> 
> possiamo far si che venga derivata da 2-3 componenti separati che vengono dati a entità diverse in modo che nessuno di loro sappia tutta la chiave
> 
> quindi al momento dello spoglio queste entità dovrebbero essere insieme fisicamente per mettere le proprie parti in un sistema verificato che scarichi i voti, decripti, verifichi ed emetta il risultato

**Comment by PalinuroSec** [comment]
accollativo

**Comment by erolm-a** [comment]
Chiudo la discussione per portarla su un repo dedicato.

https://github.com/FreeCircle/YARVIS

In questo repo si continuerà spiegando _quando_ votare e con quali criteri, il sistema dovrà essere discusso nelle issue dell'altro repo
